### PR TITLE
deps: update chksum

### PR DESCRIPTION
**Pull request by ventaquil**
Hey!

Big thanks for choosing my crate.

Here you have newer version - with comparable performance but much better code-style and API.

Thank you!

### CODE REVIEW

**Review by NikhilNarayana — APPROVED** [review]
Thanks for updating this for us

**Comment by ryanmcgrath** [comment]
@ventaquil appreciate the PR!

One thing we noticed was the CI builds [over here error out](https://github.com/project-slippi/Ishiiruka/actions/runs/5914025407/job/16039115668#step:7:1535), complaining about a missing environment variable in your build scripts. The error message is unfortunately scant on details short of "missing environment variable".

Any idea why this is? Only seems to happen there, curious if there's some environment expectation that's maybe not documented yet or something.

**Comment by ventaquil** [comment]
I will look into it as fast as I can.

**Comment by ventaquil** [comment]
Hey @ryanmcgrath!

It looks that I made some bugs in build script (the bug is caused by missing `RUSTUP_TOOLCHAIN` env var).
The fastest way to fix it is new `unstable` feature which is disabled by default - it enables build script and other unstable options.
Probably there is no need to care about build scripts for you - there are some experimental optimizations for nightly release.
I should mark those extensions as unstable/experimental from the beginning. My fault, I am very sorry. 

New release `v0.2.2` is already published, tested in Docker on my local environment and looks okay.

```
...
/workdir/Source/Core/DolphinWX/VideoConfigDiag.cpp: In member function 'void VideoConfigDiag::OnAAChanged(wxCommandEvent&)':
/workdir/Source/Core/DolphinWX/VideoConfigDiag.cpp:1704:30: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
 1704 |         vconfig.bSSAA = mode >= aa_modes.size();
      |                         ~~~~~^~~~~~~~~~~~~~~~~~
[100%] Linking CXX executable ../../../Binaries/dolphin-emu
[100%] Built target dolphin-emu
```

Please, test it on your own.

**Comment by NikhilNarayana** [comment]
Thanks for the quick turn around @ventaquil, this new version works for me

**Pull request merged**
